/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Image;
import java.net.*;
import java.awt.image.*;
import java.io.*;
import javax.imageio.*;
import gmapstatic.*;
import hr.fer.tel.pubsub.artefact.Publication;
import hr.fer.tel.pubsub.common.ReadingWritingXML;
import hr.fer.tel.pubsub.entity.NotificationListener;
import hr.fer.tel.pubsub.artefact.TripletSubscription;
import hr.fer.tel.pubsub.common.Triplet;
import hr.fer.tel.pubsub.entity.Subscriber;

/**
 *
 * @author Karl-Johan Grinnemo
 * @version 1.0
 */
public class GoogleMapsExampleGUI extends javax.swing.JFrame {
    
 /** 
  * A simple example on how to access static maps from 
  * the Google Maps API and the thin GMapStatic package.
  */

    // TODO: Supply your own Google API key.
    // Note that an API key has a limited 
    // lifetime and thus needs to be regenerated. OUR KEY ALEX: AIzaSyBR_wUAQ3iPM2e8WeoQIUw9c3xLJPRGZL8
    private static final String GOOGLE_API_KEY = "AIzaSyCMFBPuh1aTF7cYGEy22iaD2vDNmIcmX4Q";
    
    // Buses in the vicinity of MIT.
    private double theLatitude  = 42.358543;
    private double theLongitude = -71.096178;
    private int theMapWidth     = 512;
    private int theMapHeight    = 512;
    private int theZoom         = 14;
    
    private BufferedImage theMap;
    
    /**
     * Creates new form GoogleMapsExampleGUI
     */
    public GoogleMapsExampleGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        imagePanel1 = new ImagePanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Google Maps Example");

        jButton1.setText("Retrieve Map");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        imagePanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout imagePanel1Layout = new javax.swing.GroupLayout(imagePanel1);
        imagePanel1.setLayout(imagePanel1Layout);
        imagePanel1Layout.setHorizontalGroup(
            imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
        );
        imagePanel1Layout.setVerticalGroup(
            imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 352, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(imagePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        // Note: Google Static Maps API uses an
        // API key to identify your application.
        MapLookup.setLicenseKey(GOOGLE_API_KEY);
        
     
        Subscriber theSubscriber = new Subscriber("Subscriber1","PNALGORITHM","193.10.227.204",6237);
        // Don’t log subscriptions.
        theSubscriber.setLogWriting(false);
     	// Don’t print subscriptions to screen.
     	theSubscriber.setTesting(false);
     	//Connect with MoPS broker.
     	theSubscriber.connect();
     	//Publications are catched by a listener.
     	Listener theListener = new Listener();
     	theSubscriber.setNotificationListener(theListener);
     	//Create a new subscription.
     	TripletSubscription theSubscription = new TripletSubscription();
     	//Start the subscription directly.
     	theSubscription.setStartTime(System.currentTimeMillis());
     	// Time of validity: 30 seconds.
     	theSubscription.setValidity(System.currentTimeMillis() + 30000);
     	theSubscription.setProperty(new Triplet("BusId", "#10", "="));
     	//Send subscription to MoPS broker.
     	theSubscriber.subscribe(theSubscription);
        
        // Build a Google Static Map API URL of the form:
        // http://maps.googleapis.com/maps/api/staticmap?parameters.
        // See link: https://developers.google.com/maps/documentation/staticmaps/
        MapMarker theMapMarkertest = new MapMarker(42.356267, -71.098333);
        MapMarker theMapMarker1 = new MapMarker(42.357275,-71.095149);
        MapMarker theMapMarker2 = new MapMarker(42.358924,-71.097380);
        MapMarker theMapMarker3 = new MapMarker(42.360636,-71.094076);
        String theMapURIAsString = MapLookup
                .getMap(theLatitude,
                    theLongitude, 
                    theMapMarker1,
                    theMapMarker2,
                    theMapMarker3);
        try {
            
            // Retrieve map from Google Maps.
            URL theMapURI = new URL(theMapURIAsString);
            theMap = ImageIO.read(theMapURI.openStream());
            
            // Create map image scaled to size of the application window size.
            imagePanel1
                    .setImage(theMap
                        .getScaledInstance(
                            imagePanel1.getWidth(),
                            imagePanel1.getHeight(),
                            Image.SCALE_AREA_AVERAGING));
            
            // Display map image.
            imagePanel1.repaint();
                        
        } catch( IOException ex ) {
            java.util.logging.Logger.getLogger(GoogleMapsExampleGUI
                    .class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }    
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GoogleMapsExampleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GoogleMapsExampleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GoogleMapsExampleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GoogleMapsExampleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GoogleMapsExampleGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ImagePanel imagePanel1;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
